/**
 * Trade-X DOM Elements Cache
 * Caches all DOM element references to avoid repeated querySelector calls
 */

const DOMElements = {
    body: document.body,
    mainGrid: document.querySelector('.main-grid'),
    steuerungPanel: document.getElementById('steuerung-panel'),
    collapseBtn: document.getElementById('collapse-btn'),
    priceContainer: document.getElementById('price-container'),
    sellOptions: document.getElementById('sell-options'),
    buyOptions: document.getElementById('buy-options'),
    tradeSummary: document.getElementById('trade-summary'),
    tradingInsightsWrapper: document.getElementById('trading-insights-wrapper'),
    tradeModal: document.getElementById('trade-modal'),
    modalTradeDetails: document.getElementById('modal-trade-details'),
    confirmTradeBtn: document.getElementById('confirm-trade-btn'),
    cancelTradeBtn: document.getElementById('cancel-trade-btn'),
    resetBtn: document.getElementById('reset-btn'),
    fullscreenBtn: document.getElementById('fullscreen-btn'),
    fullscreenIconOpen: document.getElementById('fullscreen-icon-open'),
    fullscreenIconClose: document.getElementById('fullscreen-icon-close'),
    modeSelector: document.getElementById('mode-selector'),
    basisFeeSelector: document.getElementById('basis-fee-selector'),
    undoBtn: document.getElementById('undo-btn'),
    redoBtn: document.getElementById('redo-btn'),
    helpBtn: document.getElementById('help-btn'),
    handelsinterfacePanel: document.getElementById('handelsinterface-panel'),
    roundCounter: document.getElementById('round-counter-market'),
    endRoundBtn: document.getElementById('end-round-btn-market'),
    systemSelector: document.getElementById('economic-system-selector'),
    systemDetails: document.getElementById('system-details'),
    activeEventsContainer: document.getElementById('events-content'),
    tradeHistory: document.getElementById('tab-content-history'),
    volatilityStatus: document.getElementById('volatility-status'),
    tradeRecommendation: document.getElementById('trade-recommendation'),
    forecastText: document.getElementById('forecast-text'),
    infoModal: document.getElementById('info-modal'),
    infoModalIcon: document.getElementById('info-modal-icon'),
    infoModalTitle: document.getElementById('info-modal-title'),
    infoModalBody: document.getElementById('info-modal-body'),
    closeInfoBtn: document.getElementById('close-info-btn'),
    marketInfluenceSlider: document.getElementById('market-influence-slider'),
    influenceValue: document.getElementById('influence-value'),
    marketVolatilitySlider: document.getElementById('market-volatility-slider'),
    volatilityValue: document.getElementById('volatility-value'),
    tabHistory: document.getElementById('tab-history'),
    tabChart: document.getElementById('tab-chart'),
    tabContentChart: document.getElementById('tab-content-chart'),
    eventBannerContainer: document.getElementById('event-banner-container'),
    volatilityContainer: document.getElementById('volatility-container'),
    recommendationContainer: document.getElementById('recommendation-container'),
    resourceSetSelector: document.getElementById('resource-set-selector'),
    startMonthSelector: document.getElementById('start-month-selector'),
    seasonDisplay: document.getElementById('season-display'),
    seasonalChart: document.getElementById('seasonal-chart'),
    seasonalChartContainer: document.getElementById('seasonal-chart-container'),
    toggleSeasonalChartBtn: document.getElementById('toggle-seasonal-chart-btn'),
    seasonalChartContent: document.getElementById('seasonal-chart-content'),
};
